### ISSUE TITLE
How to change path in `include` function?

### ISSUE THREAD

**Issue by rohskopf** [cesmix-mit/LAMMPS.jl#16]
Consider this line in `fitting_snap.jl`:

`include(joinpath(dirname(pathof(LAMMPS)), "..", "examples", "snap.jl"))`

In my environment this tries to load from 

`/home/user/.julia/packages/LAMMPS/zlQdm/...`

which I think is my "private" LAMMPS package? [According to here.](https://docs.julialang.org/en/v1/manual/code-loading/)

I would like to load from my current directory instead of `/home/user/.julia/...` - is there some command or path variable I need to change?

Alternatively, is there a proper Julia way to update `/home/user/.julia/packages/LAMMPS/...`?

**Comment by vchuravy** [comment]
I am on vacation right now, but maybe @jpsamaroo or @emmanuellujan can quickly help.

In the package manager you should be able to say: `]dev LAMMPS` and then it should point to your local clone. Or just change the path locally there

**Comment by emmanuellujan** [comment]
Hi!
1. Download the repository
2. Open julia in the main folder `./LAMMPS.jl-main`
3. Type: `]dev LAMMPS`
4. Type: `include("examples/fitting_snap.jl")`

The example runs and produces the following output:

```
Potential Energy, Fitted Potential Energy, Error (%)
1695.02, 1721.56, 1.57
1716.77, 1625.86, 5.30
1727.48, 1739.46, 0.69
1690.29, 1730.16, 2.36
1709.51, 1766.40, 3.33
1749.57, 1695.72, 3.08
1752.94, 1712.39, 2.31
1765.52, 1670.54, 5.38
1725.46, 1744.22, 1.09
1732.92, 1748.40, 0.89
1687.87, 1692.51, 0.27
1726.56, 1756.36, 1.73
1685.35, 1747.74, 3.70
```
:)

**Comment by rohskopf** [comment]
Thanks guys, this worked. Another question related to this:

If I change the files in `./LAMMPS.jl/...`, it doesn't change the files in `~/.julia/dev/LAMMPS/`, where the `include` function in `fitting_snap.jl` looks. 

Are we supposed to keep these two directories the same somehow?

**Comment by emmanuellujan** [comment]
Interesting, based on what you say we can save a step:
```
$ cd ~/.julia/dev/
$ julia
(@v1.6) pkg> dev LAMMPS
julia> include("LAMMPS/examples/fitting_snap.jl")
```
and work directly in `~/.julia/dev/LAMMPS`
