### ISSUE TITLE
Macro for wrapping input lines

### ISSUE THREAD

**Issue by stefanbringuier** [cesmix-mit/LAMMPS.jl#25]
Does anyone have some thoughts on a macro to wrap lammps input script lines with `command(lmp,line)`, something along the lines of:

```julia
macro command(lmp,lines)
	lmpcmds = quote
	    for l in $(lines)
	        command($(lmp),l)
	    end
	end
	return lmpcmds
end
```

In particular, say we already have an input script we want to use, so we read it in and wrap it with the macro and then add additional commands when that are needed.

**Comment by vchuravy** [comment]
Sounds reasonable, do you want to open a PR for this?

**Comment by stefanbringuier** [comment]
> Sounds reasonable, do you want to open a PR for this?

Yep, will work on it.

**Comment by stefanbringuier** [comment]
> > Sounds reasonable, do you want to open a PR for this?
> 
> Yep, will work on it.

Tried to give this a try but seems there is some async behavior with `LMP()`, or at least I think this is the issue since its spawning a lammps instance for each command before it fails:


![image](https://user-images.githubusercontent.com/2709082/193987950-75879917-bffd-4337-bdea-44715b5f6212.png)

Note the same example works fine when using the standard approach, ex, `command(lmp,lammps-input-line)`. The `digest(example)` function call just formats a string with into a `Vector{String}` and removes `\n` and `\t`  etc.

**Comment by vchuravy** [comment]
`command` can now parse multiline statements. Maybe that's enough?
