### ISSUE TITLE
locate() and set_library!() are broken

### ISSUE THREAD

**Issue by Joroks** [cesmix-mit/LAMMPS.jl#39]
When I try to use these functions, I get the following errors:

```julia
julia> LAMMPS.locate()
ERROR: UndefVarError: `LAMMPS_jll` not defined
Stacktrace:
 [1] locate()
   @ LAMMPS C:\Users\johan\.julia\packages\LAMMPS\pSPug\src\LAMMPS.jl:15
 [2] top-level scope
   @ REPL[34]:1

julia> LAMMPS.set_library!("C:\\Users\\johan\\AppData\\Local\\LAMMPS 64-bit 17Apr2024\\bin\\liblammps.dll")
ERROR: UndefVarError: `LAMMPS_jll` not defined
Stacktrace:
 [1] set_library!(path::String)
   @ LAMMPS C:\Users\johan\.julia\packages\LAMMPS\pSPug\src\LAMMPS.jl:34
 [2] top-level scope
   @ REPL[35]:1
```

I belive this is because the LAMMPS module doesn't import API after including it.

P.S

I currently have to use my own LAMMPS installation because the Artifact doesn't have the DPD-Basic Package installed. Is it possible to include this Package with the Artifact or is this an issue with LAMMPS_jll?

**Comment by vchuravy** [comment]
Thanks for the bug report! Odd that this was broken.

> I currently have to use my own LAMMPS installation because the Artifact doesn't have the DPD-Basic Package installed. Is it possible to include this Package with the Artifact or is this an issue with LAMMPS_jll?

The build recipe is here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LAMMPS/build_tarballs.jl

You can go there and try to turn DPD on, but @mattswisher had to disable them explicitly in https://github.com/JuliaPackaging/Yggdrasil/pull/3927#issue-1060358936
