### ISSUE TITLE
Support Scatter/Gather operations

### ISSUE THREAD

**Issue by Joroks** [cesmix-mit/LAMMPS.jl#41]
currently only `lammps_gather_atoms()` is implemented.

however, I'd like to use
- `lammps_gather()`
- `lammps_gather_subset()`
- `lammps_scatter()`
- `lammps_scatter_subset()`

as well.

If I've understood the C-Library documentation (https://docs.lammps.org/Library_scatter.html#_CPPv420lammps_scatter_atomsPvPKciiPv) correctly, 

- `lammps_gather_atoms()`
- `lammps_gather_atoms_subset()`
- `lammps_scatter_atoms()`
- `lammps_scatter_atoms_subset()`

do essentially the same thing but are more restrictive (i.e. don't work with fix or compute values). So I don't think it would be necessary to implement those?

**Comment by vchuravy** [comment]
Happy to take a PR for these. I currently am short on time so I don't think I can implement it myself.

We currently don't have a high level interface to scatter:

The only use I see is https://github.com/cesmix-mit/LAMMPS.jl/blob/7201aecf8ce6886c61c546ff3035aa7626484887/examples/lj_forces.jl#L28

You could follow 
https://github.com/cesmix-mit/LAMMPS.jl/blob/7201aecf8ce6886c61c546ff3035aa7626484887/src/LAMMPS.jl#L364 to add a Julian interface for these functions.

**Comment by Joroks** [comment]
I'll get to work on it then.

**Comment by vchuravy** [comment]
Implemented in #43
