### ISSUE TITLE
Running LAMMPS from Julia.

### ISSUE THREAD

**Issue by rohskopf** [cesmix-mit/LAMMPS.jl#5]
Are there any instructions here to run LAMMPS from Julia?
For example in Python we build LAMMPS as a shared library, and then link to Python.
What's the procedure with Julia?

I ask because when I try to run the snap.jl example, I get this error:

```
ERROR: LoadError: ArgumentError: Package LAMMPS not found in current path:
- Run `import Pkg; Pkg.add("LAMMPS")` to install the LAMMPS package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:871
in expression starting at /home/drew/LAMMPS.jl/examples/snap/snap.jl:2
```

**Comment by vchuravy** [comment]
You have to use the Julia package manager to install the package (https://docs.julialang.org/en/v1/stdlib/Pkg/).

So in Julia you can do:

```
] add LAMMPS
```

Which will install LAMMPS.jl (this package) and `LAMMPS_jll` a prebuilt LAMMPS package.
Let me know if you need to do something more complicated!

If you want to change the LAMMPS.jl code you can use the `] dev LAMMPS` command.

**Comment by rohskopf** [comment]
Nice, very convenient.
