### ISSUE TITLE
Add GPU support for LAMMPS_jll

### ISSUE THREAD

**Issue by jmeziere** [cesmix-mit/LAMMPS.jl#61]
Some of my simulations would benefit from a LAMMPS lib that has cuda support. I was thinking of something like [build_tarballs.txt](https://github.com/user-attachments/files/16488959/build_tarballs.txt). Of course, this would require adding CUDA.jl as a dependency.

**Comment by vchuravy** [comment]
CUDA software has always been a bit challenging to support in a cross compilation environment like Yggdrasil/BinaryBuilder and my assumption was that folks would bring their own lammps installation for more complex scenarios.

This wouldn't add a CUDA.jl dependency, just a dependency to the hill to try and detect CUDA support.

**Comment by jmeziere** [comment]
I see. Having my own LAMMPS installation was my first go-to as well, but it requires that the CUDA toolkit be in `LD_LIBRARY_PATH` or the `rpath` of the executable. Unfortunately, CUDA warns if it is not expecting a local toolkit and a toolkit is found, and I was hoping to keep it all contained.

I think, though, that I could probably add something like a `cuLAMMPS_jll` and link it myself. That way,  you guys wouldn't have to worry about it.

The build I was basing my build_tarballs file off of was the [cufinufft_jll one](https://github.com/JuliaPackaging/Yggdrasil/tree/master/C/cufinufft). Perhaps they have a good way of handling the difficulties in a cross compilation environment? But this is my first foray into this type of thing, so I'm probably ignorant of much of the complexity.

On a side not, what does adding a dependency to the hill mean?

**Comment by vchuravy** [comment]
Do open a PR on Yggdrasil to see how hard CUDA support is. If it just works I am fine with it.

You can tell CUDA.jl to use a local tookit as well.
